### ISSUE TITLE
Ads API is deprecated

### ISSUE THREAD

**Issue by Internaturelle** [RitwikGA/FacebookReportingTool#1]
Hi,
Would you release a version with v3.0 Ads API?

**Comment by RitwikGA** [comment]
Try Replacing all "v2.11" to "v3.0" in your Code.gs file. Let me know if that works

**Comment by Internaturelle** [comment]
Hi,
yep the aPI version related error message disappear but there is something with the data formats as a new appears:
TypeError: Cannot find function split in object 2,1.DetailsDismiss

Best,
z.

Küldte a Windows 10 Posta

Feladó: Ritwik B
Elküldve: 2018. május 20., vasárnap 10:21
Címzett: RitwikGA/FacebookReportingTool
Másolatot kap: Internaturelle; Author
Tárgy: Re: [RitwikGA/FacebookReportingTool] Ads API is deprecated (#1)

Try Replacing all "v2.11" to "v3.0" in your Code.gs file. Let me know if that works

**Comment by RitwikGA** [comment]
Fixed..!!. Just copy the Cods.js file again.

**Comment by Internaturelle** [comment]
Hi @RitwikGA 
I've copied the code, 
- replaced v2.11 with v3.0
- removed ad_id form line 33 (error message on duplication)

current error message: TypeError: Cannot find function replace in object [object Object].

**Comment by ladiko** [comment]
For me it works without issues after I removed unneccessary fb_fields which I cant import to GA.

**Comment by ladiko** [comment]
@Internaturelle How does your FB_FIELDS looks like?

**Comment by Internaturelle** [comment]
I'm sorry i am in my vacay, i will get back to you 6th Aug after.

Best
Z

**Comment by leminhhai** [comment]
API is deprecated, now ver is 4.0
I can't get the facebook account
https://tppr.me/5xxNV
